# Auto-generated by the extend-hq/extend-cli release workflow on tag
# v0.7.0. Do not edit by hand; changes will be overwritten on the
# next release.
class Extend < Formula
  desc "Command-line interface for Extend"
  homepage "https://extend.ai"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.7.0/extend_v0.7.0_darwin_arm64.tar.gz"
      sha256 "d18988098696127297b708c74518dc6ce3be9466da2edc90cc195d1178a88f66"
    end
    on_intel do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.7.0/extend_v0.7.0_darwin_amd64.tar.gz"
      sha256 "0d7f168380dcfb97acfdedf298fcaf770460aebb69b7f7f84b927614ca0fa8d6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.7.0/extend_v0.7.0_linux_arm64.tar.gz"
      sha256 "b43fbebdeeb8e30b5d1a444ecf0ad2269b21e8f131e4ffe8fd032c9760536a0b"
    end
    on_intel do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.7.0/extend_v0.7.0_linux_amd64.tar.gz"
      sha256 "f7cf8ad954815053716a361b89ab938c4c80984c14e7621d6b2966a57876dde4"
    end
  end

  def install
    bin.install "extend"
  end

  def caveats
    <<~EOS
      Run 'extend setup' to finish configuring the CLI: pick a region
      and save an API key. It also installs the agent skill so coding
      agents can drive the CLI.
    EOS
  end

  test do
    system "#{bin}/extend", "--version"
  end
end
