# Auto-generated by the extend-hq/extend-cli release workflow on tag
# v0.1.15. Do not edit by hand; changes will be overwritten on the
# next release.
class Extend < Formula
  desc "Command-line interface for Extend"
  homepage "https://extend.ai"
  version "0.1.15"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.1.15/extend_v0.1.15_darwin_arm64.tar.gz"
      sha256 "0f736b145767f001e13104efd917d6d33ef68cdbe1027f5ad5afd9f170e8ab5d"
    end
    on_intel do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.1.15/extend_v0.1.15_darwin_amd64.tar.gz"
      sha256 "c15a9ccc616088470442d2efa59f2a1efbc353636613b93a65cc6cb00e63bab2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.1.15/extend_v0.1.15_linux_arm64.tar.gz"
      sha256 "18fc2939e60bb2389e9cf52e3e4981992511a0c59848e741e11c740440ce7c3b"
    end
    on_intel do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.1.15/extend_v0.1.15_linux_amd64.tar.gz"
      sha256 "2502c7f67631a6180555e589ec16046e704ce78b4cfa2f6a2aeb0750bbbc6977"
    end
  end

  def install
    bin.install "extend"
  end

  test do
    system "#{bin}/extend", "--version"
  end
end
