# Auto-generated by the extend-hq/extend-cli release workflow on tag
# v0.4.3. Do not edit by hand; changes will be overwritten on the
# next release.
class Extend < Formula
  desc "Command-line interface for Extend"
  homepage "https://extend.ai"
  version "0.4.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.4.3/extend_v0.4.3_darwin_arm64.tar.gz"
      sha256 "9cae1960074e43f4456ed9c4c836ba439f0cfec07b2e3c4ac6bef92ffef35b2b"
    end
    on_intel do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.4.3/extend_v0.4.3_darwin_amd64.tar.gz"
      sha256 "81faaa26d182278b0aecd0d6a6276a576824d18335487c5b20b9757b1c416d89"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.4.3/extend_v0.4.3_linux_arm64.tar.gz"
      sha256 "71c0fc0483f7f4664fd53d5b739051f830373a8c658cc2eb49532d2a57247419"
    end
    on_intel do
      url "https://github.com/extend-hq/extend-cli/releases/download/v0.4.3/extend_v0.4.3_linux_amd64.tar.gz"
      sha256 "c8d7f853d07be595db67de90ff970590ba1ef8b006b15c03e8f9288b96b662f9"
    end
  end

  def install
    bin.install "extend"
  end

  def caveats
    <<~EOS
      Run 'extend setup' to finish configuring the CLI: pick a region
      and save an API key. It also installs the agent skill so coding
      agents can drive the CLI.
    EOS
  end

  test do
    system "#{bin}/extend", "--version"
  end
end
